α-rename all pvar binders in refined type signatures
shingarov/MachineArithmetic pull request #192
Opened 2024-02-14 15:33 UTC by janvrany

This PR attempts to /  fixes #139 by α-renaming predicate variables in refined type signatures at parse time. IIUC this is what LH does, see https://github.com/ucsd-progsys/liquidhaskell/pull/1908. 

I'm not pretending I know what I'm doing here, but at the very least, all tests pass with these changes, including `#testAlphaClash`.

2024-02-16 22:17 UTC, shingarov requested changes
I like the fix!

I have certain desires about stuff in this PR that is *not* related to the fix.  In general, I would like to separate changes as much as possible, so we can have discussion about them separately.

The change to `DecidableRefinement` is worth discussing, in two aspects.  First, `DecidableRefinement` is on its way out of the codebase, #174 .  Second, the point of `DecidableRefinement` is to be compiled and that compilation can only happen somewhere down the processing chain, not at the beginning.  So it is not clear to me what it means for DR to hold on to its parse tree at DR's early lifestages.

Re: "refreshed" names for variables: *for now* I would like to stay as close as possible to the Haskell upstream, for debugging reasons.  This does get muddy, in at least two ways.  First, the bug this PR is addressing, breaks out of Sprite territory and goes into LH-land, so strictly speaking there is no such thing as "close to the prototype".  Second, my "VV9835" naming already deviates from the original "VV"; my incentive here was simply that I wanted to make progress while still not trusting Fixpoint's renamer.

2024-02-16 22:46 UTC, janvrany commented
> Second, the point of DecidableRefinement is to be compiled and that compilation can only happen somewhere down the processing chain, not at the beginning. So it is not clear to me what it means for DR to hold on to its parse tree at DR's early lifestages.

Commit 03f7228 does not change anything w.r.t compilation:
 * before, refinement predicate was parsed into  RB parse tree, then converted back to string and stuffed into RD (see PR #179). 
 * after (commit 03f7228 if applied), tree is converted back to string just before compilation (which is arguably stupid since Opal than parses it again, but I just did not bother for now to figure out how to tell opal to start from given parse tree).

There are cases when other code creates DR's "by hand" - `DecidableRefinement text:'some predicate string'. In this case, we parse the text to get a tree which is then stuffed into DR.

2024-02-16 23:42 UTC, shingarov commented
> tree is converted back to string just before compilation

I see, the reference to #179 explains it.  But then it's an RB tree, right? what does PetitSmalltalk do?

2024-02-16 23:44 UTC, shingarov commented
> There are cases when other code creates DR's "by hand" - `DecidableRefinement text:'some predicate string'.

Yes, that's Issue #75 .

2024-02-16 23:46 UTC, janvrany commented
> But then it's an RB tree, right? what does PetitSmalltalk do?

Yes.

2024-02-17 22:51 UTC, shingarov commented
Digging deeper: I think after all, I was wrong: #139 is NOT the same as https://github.com/ucsd-progsys/liquidhaskell/pull/1908.  The latter is about ∀ over abstract refs.  `rAllP` is only called from `bareAllP`, i.e. when parsing something like `forall <z w> . TYPE`.  To see for yourself, put a trace in `rAllP` and typecheck `basic/pos/Inc04.hs`, the breakpoint isn't hit, but `icfp15/pos/Composition.h` does hit.

2024-02-18 11:04 UTC, shingarov commented
#197 is an alternative resolution.

2024-02-26 10:34 UTC, janvrany commented
Closed if favor of #199

2024-02-26 10:34 UTC, closed without merging